name: NFT WL Hunter US/EU

on:
  schedule:
    - cron: "*/10 * * * *"   # jalan tiap 10 menit
  workflow_dispatch:
    inputs:
      extra_keyword:
        description: "Tambahan keyword (optional)"
        required: false
        default: ""

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Hunter Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          EXTRA_KEYWORD: ${{ github.event.inputs.extra_keyword }}
        run: python tracker.py
